#ifndef ICONTROLBUILDATTACKS_HPP
#define ICONTROLBUILDATTACKS_HPP

class DefBuild;
class Enemy;

/**
 * @brief Interface for managing building attacks and their targets.
 * 
 * This interface connects building attacks with the game logic, ensuring that
 * attacks generated by defensive buildings are processed, needed during-attack logic aplied to buildings,
 * and targets are selected according to specific strategies.
 */
class IControlBuildAttacks
{
public:
	/**
	 * @brief Execute an attack from a defensive building.
	 * 
	 * This method should trigger the attack logic of a defensive building (`DefBuild`),
	 * including generating and processing a `BuildAttack` object.
	 * 
	 * @param defbuild A pointer to the defensive building initiating the attack.
	 */
	virtual void attack(DefBuild* defbuild) = 0;

	/**
	 * @brief Select a target for a defensive building's attack.
	 * 
	 * This method should determine the most suitable target (`Enemy`) for the given building's attack,
	 * based on the attack strategy or other criteria.
	 * 
	 * @param defbuild A pointer to the defensive building performing the attack.
	 * @return A pointer to the selected target enemy.
	 */
	virtual Enemy* attack_strategy(DefBuild* defbuild) const = 0;

	/**
	 * @brief Update the readiness states of all buildings.
	 * 
	 * This method should iterate through all defensive buildings, advancing their readiness
	 * to ensure they are prepared for their next attack when the cooldown expires.
	 */
	virtual void processBuildsReadiness() = 0;
};

#endif
